[package]
name = "rsrpc-cli"
version = "0.24.2"
edition = "2018"
authors = ["spikehd"]

[dependencies]
rsrpc = { path = "../lib" }
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "default-tls"] }

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
]

# Also use lld on macos
[target.'cfg(target_os = "macos")']
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
]
